/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package Emeris.PROG7314.trinitymobileclient.api.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param uuid 
 * @param username 
 * @param processName 
 * @param integrity 
 * @param status 
 * @param firstSeen 
 * @param lastSeen 
 * @param campaignId 
 * @param listenerId 
 * @param payloadId 
 */


data class AgentDTO (

    @SerializedName("id")
    val id: kotlin.Int? = null,

    @SerializedName("uuid")
    val uuid: kotlin.String? = null,

    @SerializedName("username")
    val username: kotlin.String? = null,

    @SerializedName("processName")
    val processName: kotlin.String? = null,

    @SerializedName("integrity")
    val integrity: kotlin.Int? = null,

    @SerializedName("status")
    val status: kotlin.String? = null,

    @SerializedName("firstSeen")
    val firstSeen: java.time.OffsetDateTime? = null,

    @SerializedName("lastSeen")
    val lastSeen: java.time.OffsetDateTime? = null,

    @SerializedName("campaignId")
    val campaignId: kotlin.Int? = null,

    @SerializedName("listenerId")
    val listenerId: kotlin.Int? = null,

    @SerializedName("payloadId")
    val payloadId: kotlin.Int? = null

) {


}

