/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package Emeris.PROG7314.trinitymobileclient.api.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param error 
 * @param c2Port 
 * @param bindPort 
 * @param userAgent 
 * @param headers 
 * @param hosts 
 */


data class HttpListenerDto (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("error")
    val error: kotlin.String? = null,

    @SerializedName("c2Port")
    val c2Port: kotlin.Int? = null,

    @SerializedName("bindPort")
    val bindPort: kotlin.Int? = null,

    @SerializedName("userAgent")
    val userAgent: kotlin.String? = null,

    @SerializedName("headers")
    val headers: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerializedName("hosts")
    val hosts: kotlin.collections.List<kotlin.String>? = null

) {


}

