/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package Emeris.PROG7314.trinitymobileclient.api.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type 
 * @param hosts 
 * @param httpC2BindPort 
 * @param httpBindPort 
 * @param userAgent 
 * @param httpHostHeader 
 * @param hostRotationStrategy 
 * @param maxRetryStrategy 
 * @param error 
 */


data class HttpListenerDTO (

    @SerializedName("id")
    val id: kotlin.Int? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("type")
    val type: kotlin.String? = null,

    @SerializedName("hosts")
    val hosts: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("httpC2BindPort")
    val httpC2BindPort: kotlin.Int? = null,

    @SerializedName("httpBindPort")
    val httpBindPort: kotlin.Int? = null,

    @SerializedName("userAgent")
    val userAgent: kotlin.String? = null,

    @SerializedName("httpHostHeader")
    val httpHostHeader: kotlin.String? = null,

    @SerializedName("hostRotationStrategy")
    val hostRotationStrategy: kotlin.String? = null,

    @SerializedName("maxRetryStrategy")
    val maxRetryStrategy: kotlin.String? = null,

    @SerializedName("error")
    val error: kotlin.String? = null

) {


}

