/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package Emeris.PROG7314.trinitymobileclient.api.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param domain 
 * @param user 
 * @param command 
 * @param arguements 
 */


data class RunAsDTO (

    @SerializedName("domain")
    val domain: kotlin.String? = null,

    @SerializedName("user")
    val user: kotlin.String? = null,

    @SerializedName("command")
    val command: kotlin.String? = null,

    @SerializedName("arguements")
    val arguements: kotlin.String? = null

) {


}

